server:
    port: 8081

spring:
    application:
        name: auth-service

    datasource:
        url: jdbc:mysql://localhost:3306/resume_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:root}

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        redirect-uri: "http://localhost:8080/login/oauth2/code/google"
                        scope:
                            - email
                            - profile
                provider:
                    google:
                        user-name-attribute: email

jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        prefer-ip-address: false
        hostname: localhost
        instance-id: ${spring.application.name}:${random.value}
