server:
    port: 8083

spring:
    application:
        name: export-service

    datasource:
        url: jdbc:mysql://localhost:3306/resume_export_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:root}

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

    instance:
        prefer-ip-address: true

# AWS S3 Configuration (Soft Coded - Enterprise Standard)
aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    s3:
        bucket-name: ${AWS_BUCKET_NAME:resumepilot-pdf-exports-bhai}
        region: ${AWS_REGION:ap-southeast-2}
