server:
    port: 8761

spring:
    config:
        import:
            - optional:file:D:/ResumePilot/.env[.properties]
            - optional:file:../.env[.properties]
            - optional:file:.env[.properties]

    application:
        name: eureka-server

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
    instance:
        hostname: ${EUREKA_INSTANCE_HOSTNAME:${EUREKA_HOSTNAME:localhost}}
